apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gateway-ns
resources:
  - ./deployment.yaml
  - ./service.yaml
  - ./ingress.yaml
  - ./volume.yaml
  - ./namespace.yaml
commonLabels:
  app: p-ser-gateway