apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gateway-ns
resources:
  - ./deployment.yaml
  - ./service.yaml
  - ./ingress.yaml
  - ./namespace.yaml
commonLabels:
  app: p-ser-gateway
configMapGenerator:
  - name: app-config
    files:
      - config/application.yaml